export { default as CloseBlack } from "./close-black.png"
export { default as CloseWhite } from "./close-white.png"
export { default as ClosePrimary } from "./close-primary.png"
export { default as search } from "./search.png"
export { default as DownArrow } from "./down-arrow.png"
export { default as Sort } from "./sort.png"
export { default as Earth } from "./globe.png"
export { default as Logout } from "./logout.png"

export { default as StandardInformationManagement } from "./home.png"
export { default as TaskManagement } from "./calendar.png"
export { default as ProductionManagement } from "./chart.png"
export { default as ProjectManagement } from "./schedule.png"
export { default as SalesManagement } from "./add-user.png"
export { default as QualityManagement } from "./setting.png"
export { default as InventoryInOutManagement } from "./cart.png"
export { default as InventoryManagement } from "./like.png"
export { default as FacilityManagement } from "./list.png"

export { default as NaviClose } from "./double-angle-left.png"
export { default as NaviOpen } from "./double-angle-right.png"
